import {
  Eye,
  LayoutGrid,
  Search,
  GitCompare,
  ArrowDownWideNarrow,
  ArrowUpWideNarrow,
  SlidersHorizontal,
  ArrowDownToLine,
  MessageSquareText,
  Truck,
  Ticket,
  ShoppingCart,
  XCircle,
  Heart,
  ShoppingBag,
  CreditCard,
  Ban,
  CheckCircle2,
  LogOut,
  RotateCcw,
  Ruler,
  ZoomIn,
  PlayCircle,
  MousePointerClick,
  Mail,
  Headset,
  ArrowDownRight,
  Gift,
  Circle,
  type LucideIcon,
} from "lucide-react";
import type { EventType } from "@/types/events";

export const EVENT_ICONS: Record<EventType, LucideIcon> = {
  view_product: Eye,
  view_category: LayoutGrid,
  search: Search,
  compare_products: GitCompare,
  sort_price_low: ArrowDownWideNarrow,
  sort_price_high: ArrowUpWideNarrow,
  filter_apply: SlidersHorizontal,
  scroll_deep: ArrowDownToLine,
  read_reviews: MessageSquareText,
  view_shipping_info: Truck,
  apply_coupon_attempt: Ticket,
  add_to_cart: ShoppingCart,
  remove_from_cart: XCircle,
  add_to_wishlist: Heart,
  view_cart: ShoppingBag,
  begin_checkout: CreditCard,
  abandon_checkout: Ban,
  purchase: CheckCircle2,
  exit: LogOut,
  return_visit: RotateCcw,
  view_size_guide: Ruler,
  zoom_image: ZoomIn,
  watch_video: PlayCircle,
  click_recommendation: MousePointerClick,
  email_signup: Mail,
  chat_support: Headset,
  price_drop_view: ArrowDownRight,
  view_gift_options: Gift,
};

export function getEventIcon(event: string): LucideIcon {
  return EVENT_ICONS[event as EventType] ?? Circle;
}
